name: Oper Guide

on:
  push:
    branches:
      - main
    paths:
      - 'doc/oper-guide/**'
  pull_request:
    branches:
      - main
    paths:
      - 'doc/oper-guide/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            python-sphinx \
            texinfo \
            # EOF
      - uses: actions/checkout
        with:
          persist-credentials: false
          submodules: recursive
      - name: Build Oper Guide
        run: make -C doc/oper-guide html man info
